### ISSUE TITLE
Re-allocating SMEM data structures due to enc_qdb - Segmentation fault

### ISSUE THREAD

**Issue by ChristosMatzoros** [bwa-mem2/bwa-mem2#167]
Hello,

I try to map 10K sequences of size 10K each [(input)](https://drive.google.com/file/d/1m_uoL-0ICD2b8uDWjsIZhHoG9f3hFcBZ/view?usp=sharing) 
I execute like this: ./bwa-mem2 mem -t 1 prefix input.fq  > output.sam

And I take the following result (with segmentation fault):

`------------------------------------------
1. Memory pre-allocation for Chaining: 139.3584 MB
2. Memory pre-allocation for BSW: 239.6170 MB
3. Memory pre-allocation for BWT: 77.3142 MB
------------------------------------------
* Threads used (compute): 1
* No. of pipeline threads: 2

[0000] read_chunk: 10000000, work_chunk_size: 10000000, nseq: 1000
	[0000][ M::kt_pipeline] read 1000 sequences (10000000 bp)...
[0000] Calling mem_process_seqs.., task: 0
[0000] 1. Calling kt_for - worker_bwt
[0000] Re-allocating SMEM data structures due to enc_qdb
Segmentation fault (core dumped)
`

Is the problem the size of the reads or it can be something else? (My machine has over 120 GB available so this is not a memory problem on my side.)

Best

**Comment by yuk12** [comment]
Let me look into this.

**Comment by Zou-Pan** [comment]
> Hello,
> 
> I try to map 10K sequences of size 10K bases each [(input)](https://drive.google.com/file/d/1m_uoL-0ICD2b8uDWjsIZhHoG9f3hFcBZ/view?usp=sharing) I execute like this: ./bwa-mem2 mem -t 1 prefix input.fq > output.sam
> 
> And I take the following result (with segmentation fault):
> 
> `------------------------------------------
> 
> 1. Memory pre-allocation for Chaining: 139.3584 MB
> 2. Memory pre-allocation for BSW: 239.6170 MB
> 3. Memory pre-allocation for BWT: 77.3142 MB
> 
> * Threads used (compute): 1
> * No. of pipeline threads: 2
> 
> [0000] read_chunk: 10000000, work_chunk_size: 10000000, nseq: 1000 [0000][ M::kt_pipeline] read 1000 sequences (10000000 bp)... [0000] Calling mem_process_seqs.., task: 0 [0000] 1. Calling kt_for - worker_bwt [0000] Re-allocating SMEM data structures due to enc_qdb Segmentation fault (core dumped) `
> 
> Is the problem may be the size of the reads or it can be something else? (My machine has over 120 GB available so this is not a memory problem on my side.)
> 
> Best

I have the same question. Mem is 187 GB available on my machine.

**Comment by yuk12** [comment]
Some issue in the reallocation block, I am working on fixing this.

**Comment by yuk12** [comment]
Fixed the issue, Please try with the latest commit.

**Comment by tscott3LUC** [comment]
I have the same problem as above. Changed to the latest commit and still having the issue despite the changes.

**Comment by jenzyy97** [comment]
I ran with latest bwa-mem2 v2.2.1 and encountered the same problem. I used bwa-mem1 instead and it worked.

**Comment by stepwise-ai-dev** [comment]
> I ran with latest bwa-mem2 v2.2.1 and encountered the same problem. I used bwa-mem1 instead and it worked.

I'm encountering the same problem (I installed [bwa-mem2 via conda](https://anaconda.org/bioconda/bwa-mem2)). @jenzyy97 when you say you used bwa-mem1, do you mean that you used "bwa mem" from the [original bwa code](https://github.com/lh3/bwa)?

**Comment by vasimuddin** [comment]
I've a fix for it, will try to push it this week.
