### ISSUE TITLE
segmentation fault (core dumped) error and difference with bwa-mem and bwa-mem2

### ISSUE THREAD

**Issue by ddhb** [bwa-mem2/bwa-mem2#34]
pre-information is below
computer spec = Ubuntu, 80core, 760GB ram
bwa version = 2.0pre1
testfiles = 1.7G, 1.7G (paired)
Ref genome = GRCh38 

cmd doesn't work.
bwa-mem2 mem -t 75 ref/grch38.fa ../test1.fastq.gz ../test2.fastq.gz > out.sam
```

-----------------------------
Executing in AVX2 mode!!
-----------------------------
Ref file: ref/grch38.fa
Entering FMI_search
reference seq len = 6176572803
count
0,      1
1,      1811087986
2,      3088286402
3,      4365484818
4,      6176572803

Reading other elements of the index from files ref/grch38.fa
prefix: ref/grch38.fa
[M::bwa_idx_load_ele] read 0 ALT contigs
Done reading Index!!
Reading reference genome..
Binary seq file = ref/grch38.fa.0123
Reference genome size: 6176572802 bp
Done readng reference genome !!

readLen: 151

[0000] 1: Calling process()

Threads used (compute): 75
Projected #read in a task: 4966897
------------------------------------------
Memory pre-allocation for chaining: 159218850232
Memory pre-allocation for BSW: 17971276800
Memory pre-allocation for BWT: 4638883200
------------------------------------------
No. of pipeline threads: 2
[0000] read_chunk: 750000000, work_chunk_size: 750000088, nseq: 4966888
        [0000][ M::kt_pipeline] read 4966888 sequences (750000088 bp)...
[0000] 2. Calling mem_process_seqs.., task: 0
[0000] 3. Calling kt_for - worker_bwt
Segmentation fault (core dumped)

```

but it did work well
bwa-mem2 mem -t 40 ref/grch38.fa ../test1.fastq.gz ../test2.fastq.gz > out.sam (20G)

also 'bwa-mem' works too. but file size with made from 'bwa-mem' is 26G. Is it just difference from algorithm? is it negligible?

Thanks

**Comment by ddhb** [comment]
I tested on various threads count.
T40, T50, T60 Okay.
T70, T80, T65 not working.

**Comment by yuk12** [comment]
Please try with the latest commit. Release 1 is a bit old. We are in the process of releasing a new one.

**Comment by a00101** [comment]
I got some errors from git source install

```

root@name:bwa-mem2# make
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/fastmap.cpp -o src/fastmap.o
src/fastmap.cpp: In function ‘int64_t get_limit_fsize(FILE*, int64_t, char*, char*)’:
src/fastmap.cpp:120:34: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets((char*) buf1, len, fpp);
                                  ^
src/fastmap.cpp:121:34: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets((char*) buf1, len, fpp);
                                  ^
src/fastmap.cpp: In function ‘int main_mem(int, char**)’:
src/fastmap.cpp:921:33: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   fread(ref_string, 1, rlen, fr);
                                 ^
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/bwtindex.cpp -o src/bwtindex.o
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/utils.cpp -o src/utils.o
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/kthread.cpp -o src/kthread.o
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/kstring.cpp -o src/kstring.o
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/ksw.cpp -o src/ksw.o
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/bntseq.cpp -o src/bntseq.o
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/bwamem.cpp -o src/bwamem.o
src/bwamem.cpp: In function ‘void mem_process_seqs(mem_opt_t*, const bntseq_t*, const uint8_t*, int64_t, int, bseq1_t*, const mem_pestat_t*, worker_t&)’:
src/bwamem.cpp:1281:68: warning: '0' flag ignored with precision and ‘%d’ gnu_printf format [-Wformat=]
  fprintf(stderr, "[%0.4d] 3. Calling kt_for - worker_bwt\n", myrank);
                                                                    ^
src/bwamem.cpp:1285:68: warning: '0' flag ignored with precision and ‘%d’ gnu_printf format [-Wformat=]
  fprintf(stderr, "[%0.4d] 3. Calling kt_for - worker_aln\n", myrank);
                                                                    ^
src/bwamem.cpp:1305:69: warning: '0' flag ignored with precision and ‘%d’ gnu_printf format [-Wformat=]
  fprintf(stderr, "[%0.4d] 10. Calling kt_for - worker_sam\n", myrank);
                                                                     ^
src/bwamem.cpp:1312:54: warning: '0' flag ignored with precision and ‘%d’ gnu_printf format [-Wformat=]
    __func__, n, cputime() - ctime, realtime() - rtime);
                                                      ^
src/bwamem.cpp: In function ‘void mem_chain2aln_across_reads_V2(const mem_opt_t*, const bntseq_t*, const uint8_t*, bseq1_t*, int, mem_chain_v*, mem_alnreg_v*, mem_cache*, int64_t, int64_t, int64_t, int)’:
src/bwamem.cpp:2016:38: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
   _mm_prefetch((const char*) query, 0);
                                      ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/emmintrin.h:31:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bwamem.h:39,
                 from src/bwamem.cpp:31:
/usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:52:1: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
 _mm_prefetch (const void *__P, enum _mm_hint __I)
 ^
src/bwamem.cpp:2034:52: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
    _mm_prefetch((const char*) (srtg + spos + 64), 0);
                                                    ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/emmintrin.h:31:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bwamem.h:39,
                 from src/bwamem.cpp:31:
/usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:52:1: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
 _mm_prefetch (const void *__P, enum _mm_hint __I)
 ^
src/bwamem.cpp:2035:41: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
    _mm_prefetch((const char*) (lim_g), 0);
                                         ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/emmintrin.h:31:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bwamem.h:39,
                 from src/bwamem.cpp:31:
/usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:52:1: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
 _mm_prefetch (const void *__P, enum _mm_hint __I)
 ^
src/bwamem.cpp:2072:38: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
    _mm_prefetch((const char*) rseq, 0);
                                      ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/emmintrin.h:31:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bwamem.h:39,
                 from src/bwamem.cpp:31:
/usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:52:1: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
 _mm_prefetch (const void *__P, enum _mm_hint __I)
 ^
src/bwamem.cpp:2132:77: warning: '0' flag ignored with precision and ‘%d’ gnu_printf format [-Wformat=]
       fprintf(stderr, "[LOG][%0.4d] Re-allocating seqPairArrays Left\n", tid);
                                                                             ^
src/bwamem.cpp:2207:79: warning: '0' flag ignored with precision and ‘%d’ gnu_printf format [-Wformat=]
       fprintf(stderr, "[LOG] [%0.4d] Re-allocating seqPairArrays Right\n", tid);
                                                                               ^
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/profiling.cpp -o src/profiling.o
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/bandedSWA.cpp -o src/bandedSWA.o
src/bandedSWA.cpp: In member function ‘void BandedPairWiseSW::smithWatermanBatchWrapper16(SeqPair*, uint8_t*, uint8_t*, int32_t, uint16_t, int8_t)’:
src/bandedSWA.cpp:3755:64: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
      _mm_prefetch((const char*) seqBufRef + (int64_t)spf.idr, 0);
                                                                ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/emmintrin.h:31:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bandedSWA.cpp:30:
/usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:52:1: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
 _mm_prefetch (const void *__P, enum _mm_hint __I)
 ^
src/bandedSWA.cpp:3756:69: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
      _mm_prefetch((const char*) seqBufRef + (int64_t)spf.idr + 64, 0);
                                                                     ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/emmintrin.h:31:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bandedSWA.cpp:30:
/usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:52:1: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
 _mm_prefetch (const void *__P, enum _mm_hint __I)
 ^
src/bandedSWA.cpp:3799:64: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
      _mm_prefetch((const char*) seqBufQer + (int64_t)spf.idq, 0);
                                                                ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/emmintrin.h:31:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bandedSWA.cpp:30:
/usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:52:1: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
 _mm_prefetch (const void *__P, enum _mm_hint __I)
 ^
src/bandedSWA.cpp:3800:69: warning: invalid conversion from ‘int’ to ‘_mm_hint’ [-fpermissive]
      _mm_prefetch((const char*) seqBufQer + (int64_t)spf.idq + 64, 0);
                                                                     ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/emmintrin.h:31:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/pmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/tmmintrin.h:31,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/smmintrin.h:32,
                 from src/bandedSWA.h:42,
                 from src/bandedSWA.cpp:30:
/usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:52:1: note:   initializing argument 2 of ‘void _mm_prefetch(const void*, _mm_hint)’
 _mm_prefetch (const void *__P, enum _mm_hint __I)
 ^
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/FMI_search.cpp -o src/FMI_search.o
src/FMI_search.cpp: In constructor ‘FMI_search::FMI_search(char*)’:
src/FMI_search.cpp:55:60: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(&reference_seq_len, sizeof(int64_t), 1, cpstream);
                                                            ^
src/FMI_search.cpp:65:51: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(&count[0], sizeof(int64_t), 5, cpstream);
                                                   ^
src/FMI_search.cpp:68:57: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(cp_occ, sizeof(CP_OCC), cp_occ_size, cpstream);
                                                         ^
src/FMI_search.cpp:76:67: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(sa_ms_byte, sizeof(int8_t), reference_seq_len, cpstream);
                                                                   ^
src/FMI_search.cpp:77:69: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(sa_ls_word, sizeof(uint32_t), reference_seq_len, cpstream);
                                                                     ^
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/read_index_ele.cpp -o src/read_index_ele.o
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/bwamem_pair.cpp -o src/bwamem_pair.o
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/kswv.cpp -o src/kswv.o
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/bwa.cpp -o src/bwa.o
src/bwa.cpp: In function ‘bseq1_t* bseq_read(int64_t, int*, void*, void*, FILE*, int, int64_t*)’:
src/bwa.cpp:123:32: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
    fgets((char*) buf, len, fpp);
                                ^
src/bwa.cpp:126:32: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
    fgets((char*) buf, len, fpp);
                                ^
src/bwa.cpp:129:33: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets((char*) buf, len, fpp);
                                 ^
src/bwa.cpp:131:33: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fgets((char*) buf, len, fpp);
                                 ^
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/bwamem_extra.cpp -o src/bwamem_extra.o
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/bwtbuild.cpp -o src/bwtbuild.o
src/bwtbuild.cpp: In function ‘int build_index(const char*)’:
src/bwtbuild.cpp:721:64: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘long long unsigned int’ [-Wformat=]
     fprintf(stderr, "init ticks = %ld\n", __rdtsc() - startTick);
                                                                ^
src/bwtbuild.cpp:753:70: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘long long unsigned int’ [-Wformat=]
     fprintf(stderr, "binary seq ticks = %ld\n", __rdtsc() - startTick);
                                                                      ^
src/bwtbuild.cpp:763:71: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘long long unsigned int’ [-Wformat=]
     fprintf(stderr, "build index ticks = %ld\n", __rdtsc() - startTick);
                                                                       ^
ar rcs libbwa.a src/fastmap.o src/bwtindex.o src/utils.o src/kthread.o src/kstring.o src/ksw.o src/bntseq.o src/bwamem.o src/profiling.o src/bandedSWA.o src/FMI_search.o src/read_index_ele.o src/bwamem_pair.o src/kswv.o src/bwa.o src/bwamem_extra.o src/bwtbuild.o
g++ -c -g -O3 -fpermissive -msse4.1  -DENABLE_PREFETCH -DPAIRED_END=1 -DMAINY=0 -DSAIS=1 -DDEB=0 -DRDT=0 -DMAXI=0 -DNEW=1 -DSORT_PAIRS=0   src/main.cpp -o src/main.o
g++ -g -O3 -fpermissive -msse4.1  libbwa.a src/main.o -o bwa-mem2 -lpthread -lm -lz -L. -lbwa
./libbwa.a(fastmap.o): In function `process(void*, gzFile_s*, gzFile_s*, int) [clone .isra.5]':
/bwa-mem2/src/fastmap.cpp:547: undefined reference to `pthread_create'
/bwa-mem2/src/fastmap.cpp:550: undefined reference to `pthread_join'
./libbwa.a(fastmap.o): In function `main_mem(int, char**)':
/bwa-mem2/src/fastmap.cpp:936: undefined reference to `gzopen'
/bwa-mem2/src/fastmap.cpp:956: undefined reference to `gzopen'
./libbwa.a(utils.o): In function `err_xzopen_core':
/bwa-mem2/src/utils.cpp:79: undefined reference to `gzdopen'
/bwa-mem2/src/utils.cpp:84: undefined reference to `gzopen'
./libbwa.a(utils.o): In function `err_gzread':
/bwa-mem2/src/utils.cpp:144: undefined reference to `gzread'
/bwa-mem2/src/utils.cpp:144: undefined reference to `gzread'
/bwa-mem2/src/utils.cpp:144: undefined reference to `gzread'
/bwa-mem2/src/utils.cpp:144: undefined reference to `gzread'
/bwa-mem2/src/utils.cpp:144: undefined reference to `gzread'
./libbwa.a(utils.o):/bwa-mem2/src/utils.cpp:144: more undefined references to `gzread' follow
./libbwa.a(utils.o): In function `err_gzclose':
/bwa-mem2/src/utils.cpp:269: undefined reference to `gzclose'
/bwa-mem2/src/utils.cpp:272: undefined reference to `zError'
./libbwa.a(utils.o): In function `err_gzread.part.0':
/bwa-mem2/src/utils.cpp:149: undefined reference to `gzerror'
./libbwa.a(kthread.o): In function `kt_for(void (*)(void*, int, int, int), void*, int)':
/bwa-mem2/src/kthread.cpp:120: undefined reference to `pthread_create'
/bwa-mem2/src/kthread.cpp:123: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
Makefile:86: recipe for target 'bwa-mem2' failed
make: *** [bwa-mem2] Error 1
```

**Comment by a00101** [comment]
You said, you will release soon.
Okay.

I'll be waiting for this.

Thanks

**Comment by yuk12** [comment]
Sure, We plan to release it very soon.
Your log says that "undefined reference to `pthread_create'" and "undefined reference to `gzdopen'". Could you check whether your OS supports these libraries? Installing these libraries should solve the problem.

**Comment by a00101** [comment]
is the new version released?

**Comment by yuk12** [comment]
We have released a new version. Please try that.

**Comment by Mengjintao** [comment]
We test the newest version. This bug is still here. (the commit used in our test is 966cd1e0e7869c45ae7a93287612be6697406051)

------------------------------------------
1. Memory pre-allocation for Chaining: 139.3584 MB
2. Memory pre-allocation for BSW: 239.6170 MB
3. Memory pre-allocation for BWT: 77.3142 MB
------------------------------------------
* Threads used (compute): 1
* No. of pipeline threads: 2

[0000] read_chunk: 10000000, work_chunk_size: 10000126, nseq: 66226
        [0000][ M::kt_pipeline] read 66226 sequences (10000126 bp)...
[0000] Calling mem_process_seqs.., task: 0
[0000] 1. Calling kt_for - worker_bwt
Segmentation fault (core dumped)

**Comment by Mengjintao** [comment]
We tried both g++ and icpc, and also the commit (ebc2378) provided by your previous replies. They all failed with "Segmentation fault (core dumped)".

**Comment by yuk12** [comment]
Did you re-build the index using this latest commit? what is the memory capacity, the index needs 10+ GB memory?
